version: '3.8'
services:

  minecraft:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    volumes:
      - /home/docker/minecraft/data:/data
    environment:
      EULA: 'TRUE'
      VERSION: 'latest'
    restart: unless-stopped
    
  minecraft-bedrock:
    image: itzg/minecraft-bedrock-server
    ports:
      - 19132:19132/udp
    volumes:
      - /home/docker/minecraft-bedrock/data:/data
    environment:
      EULA: 'TRUE'
      VERSION: 'latest'
    restart: unless-stopped

  minecraft-overviewer:
    image: marctv/minecraft-overviewer
    ports:
      - 25575:25575
    volumes:
      - /home/docker/minecraft/data/world:/tmp/server/world
      - /home/docker/minecraft/minecraft_map:/output
      - /home/docker/minecraft/textures:/tmp/textures
    command: ["--texturepath", "/tmp/textures", "/tmp/server/world", "/output"]
    restart: unless-stopped
